name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-yara:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y automake libtool make gcc pkg-config libssl-dev libjansson-dev

      - name: Download YARA
        run: |
          curl -L -O https://github.com/VirusTotal/yara/archive/refs/tags/v4.4.0.tar.gz
          tar -zxf v4.4.0.tar.gz
          cd yara-4.4.0

      - name: Compile and install YARA
        run: |
          cd yara-4.4.0
          ./bootstrap.sh
          ./configure
          make
          sudo make install

      - name: Build
        run: go build -v ./...

